package options

import (
	"time"

	"gokiteconnect-master/models"
)

// OptionType represents call or put option
type OptionType string

const (
	Call OptionType = "CE"
	Put  OptionType = "PE"
)

// OptionInstrument represents an option instrument with metadata
type OptionInstrument struct {
	InstrumentToken uint32
	ExchangeToken   uint32
	Tradingsymbol   string
	Name            string
	Exchange        string
	Segment         string
	InstrumentType  OptionType // CE or PE
	StrikePrice     float64
	Expiry          time.Time
	TickSize        float64
	LotSize         int
	LastPrice       float64
}

// OptionChain represents a complete option chain for an underlying
type OptionChain struct {
	Underlying      string
	UnderlyingToken uint32
	UnderlyingPrice float64 // Current price of the underlying
	Expiry          time.Time
	Strikes         map[float64]*StrikeData
	LastUpdated     time.Time
}

// StrikeData contains both call and put data for a strike
type StrikeData struct {
	Strike      float64
	Call        *OptionData
	Put         *OptionData
	LastUpdated time.Time
}

// OptionData contains real-time data for a single option
type OptionData struct {
	InstrumentToken uint32
	Tradingsymbol   string
	Type            OptionType
	Strike          float64
	Expiry          time.Time

	// Market Data (from ticks)
	LastPrice   float64
	BidPrice    float64
	AskPrice    float64
	BidQty      uint32
	AskQty      uint32
	Volume      uint32
	OI          uint32 // Open Interest
	LastUpdated time.Time

	// Calculated Fields
	IV    float64 // Implied Volatility
	Delta float64
	Gamma float64
	Theta float64
	Vega  float64

	// Greeks calculated from market data
	IntrinsicValue float64
	TimeValue      float64
}

// Position represents an open option position
type Position struct {
	InstrumentToken uint32
	Tradingsymbol   string
	Type            OptionType
	Strike          float64
	Expiry          time.Time
	Quantity        int // Negative for short positions
	AveragePrice    float64
	CurrentPrice    float64
	UnrealizedPnL   float64
	RealizedPnL     float64
	EntryTime       time.Time
}

// Signal represents a trading signal generated by strategy
type Signal struct {
	Action          string // "BUY", "SELL", "EXIT"
	InstrumentToken uint32
	Tradingsymbol   string
	Type            OptionType
	Strike          float64
	Expiry          time.Time
	Quantity        int
	Reason          string
	Priority        int // Higher = more urgent
	Timestamp       time.Time
}

// RiskParams defines risk management parameters
type RiskParams struct {
	MaxPositionSize      int     // Max contracts per position
	MaxPortfolioDelta    float64 // Max portfolio delta
	MaxPortfolioGamma    float64 // Max portfolio gamma
	MaxPortfolioTheta    float64 // Max portfolio theta
	MaxPortfolioVega     float64 // Max portfolio vega
	MaxLossPerTrade      float64 // Max loss per trade
	MaxDailyLoss         float64 // Max daily loss
	MaxMarginUtilization float64 // Max margin % (0-1)
	StopLossPercent      float64 // Stop loss % of premium
	ProfitTargetPercent  float64 // Profit target % of premium
}

// UpdateFromTick updates option data from a market tick
func (od *OptionData) UpdateFromTick(tick models.Tick) {
	od.LastPrice = tick.LastPrice
	od.LastUpdated = time.Now()

	// Update from depth if available
	if len(tick.Depth.Buy) > 0 {
		od.BidPrice = tick.Depth.Buy[0].Price
		od.BidQty = tick.Depth.Buy[0].Quantity
	}
	if len(tick.Depth.Sell) > 0 {
		od.AskPrice = tick.Depth.Sell[0].Price
		od.AskQty = tick.Depth.Sell[0].Quantity
	}

	od.Volume = tick.VolumeTraded
	od.OI = tick.OI

	//fmt.Println("OptionData Updated :", od.Tradingsymbol, " LastPrice: ", od.LastPrice, " BidPrice: ", od.BidPrice, " AskPrice: ", od.AskPrice, " Volume: ", od.Volume, " OI: ", od.OI)
}
